// Configures the GPT class to interact with OpenAI's API, facilitating chat-based interactions.


import { config } from 'dotenv';
import OpenAI, { ClientOptions } from "openai";

interface ChatCompletionMessageParam {
  role: 'system' | 'user';
  content: string;
  name: 'System' | 'User';
}

config(); // Load environment variables.

if (!process.env.OPENAI_API_KEY) {
  throw new Error('OPENAI_API_KEY is not defined in your environment variables.');
}

const clientOptions: ClientOptions = {
  apiKey: process.env.OPENAI_API_KEY,
};

const openai = new OpenAI(clientOptions);

// Manages sending user messages to OpenAI and receiving AI-generated responses.
export class GPT {
  
  /**
   * Sends a user message to OpenAI, returning the AI's response.
   * 
   * @param userMessage The user's input message.
   * @returns The response generated by OpenAI's model.
   */
  async sendMessage(userMessage: string) {
    const messages: ChatCompletionMessageParam[] = [
      { role: "system", content: "You are a helpful assistant.", name: "System" },
      { role: "user", content: userMessage, name: "User" }
    ];

    const completion = await openai.chat.completions.create({
      messages: messages,
      model: "gpt-3.5-turbo",
    });

    return completion.choices[0].message.content;
  }
}
